server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank-account-db
    username: postgres
    password: postgres
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      naming.implicit-strategy : org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

axon:
  amqp:
    exchange: bank-account.events
  eventhandling:
    processors:
      amqpEvents:
        source: complaintEventsMethod